version: '3.9'

services:
  rails:
    build:
      context: .
      args:
        HOST_UID: ${HOST_UID:-1000}
        HOST_GID: ${HOST_GID:-1000}
        APP_DIR: /app
    volumes:
      - .:/app:cached
    ports:
      - 3000:3000
    command: /bin/sh -c "rm -f tmp/pids/server.pid && rdbg --nonstop --open --command -- rails server --binding=0.0.0.0"
    tty: true
