version: '3.9'

services:
  rails:
    build:
      context: .
      args:
        HOST_UID: ${HOST_UID:-1000}
        HOST_GID: ${HOST_GID:-1000}
        APP_DIR: /app
    volumes:
      - .:/app:cached
    tty: true
